In [1]:
import numpy as np

In [2]:
a = np.array([0,1,2,3])

In [3]:
a

array([0, 1, 2, 3])

ndim = returns the dimention of the array

shape = returns the shape of an array in terms of (row,column)

len = returns the length of an array which is nothing but the number of rows

In [4]:
b = np.array([[9,7,5,3,1],[0,8,6,4,2]])

In [5]:
b

array([[9, 7, 5, 3, 1],
       [0, 8, 6, 4, 2]])

In [6]:
b.ndim

2

In [7]:
b.shape

(2, 5)

In [8]:
len(b)

2

Functions for creating arrays

arange(): evenly spaced array

linspace(): evenly spaced by number of points(linearly)

ones(): matrix of ones

eye(): identity matrix

zeros(): zero matrix

diag(): values in diagonal only

rand(): array of random numbers

seed(): set up the seed

In [9]:
arangeArray = np.arange(10) #gives an array of 10 evenly seprated values

In [10]:
arangeArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arangeArray1 = np.arange(1, 10, 2) #start at 1, end at 10 and seperate by 2
arangeArray1

array([1, 3, 5, 7, 9])

In [12]:
linspaceArray1 = np.linspace(1, 10, 5, endpoint=False) #start at 1, end at 10, number of points 5 and it won't consider 10 because endpoint=False
linspaceArray1

array([1. , 2.8, 4.6, 6.4, 8.2])

In [13]:
linspaceArray2 = np.linspace(1, 10, 5, endpoint=True) #start at 1, end at 10, number of points 5 and it will consider 10 because endpoint=True
print(linspaceArray2)

print('If consdering the ending number than we can ignore endpoint=True arg');

[ 1.    3.25  5.5   7.75 10.  ]
If consdering the ending number than we can ignore endpoint=True arg


In [14]:
onesArray = np.ones((3,3)) #this will return 2 dimentional matrix which will have all values as 1
onesArray

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
iArray = np.eye(3) #this will return identity matrix of 3 dimentional(3*3)
iArray

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
diagonalArray = np.diag(np.array([2,4,6,8,10])) #this will return a matrix whoes values are in diagonal only
diagonalArray

array([[ 2,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  6,  0,  0],
       [ 0,  0,  0,  8,  0],
       [ 0,  0,  0,  0, 10]])

In [17]:
emptyArray = np.empty([4,2]) #returns a random array
emptyArray

array([[0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 5.86949987e-321],
       [1.24610926e-306, 8.90060779e-307]])

In [18]:
np.random.seed(1234) #seed helps to generate pseudo random numbers by using given number
random1 = np.random.rand(4) #generates random numbers
print(random1)

random2 = np.random.randn(4) #gaussian
print(random2)

print('\nBy using random seed function it will generate same pseudo random numbers every time if we specify a particular number')

[0.19151945 0.62210877 0.43772774 0.78535858]
[-0.72058873  0.88716294  0.85958841 -0.6365235 ]

By using random seed function it will generate same pseudo random numbers every time if we specify a particular number


Below is the code for multi dimentional array/vector/metrix by using numpy random function

In [19]:
np.random.seed(121212)  #if any number is not defined it will generate different numbers every time
randArray1 = np.random.rand(3,3)
print(randArray1)
print(randArray1.ndim, 'dimention')
print(randArray1.shape, 'shape')
print('length of an array ',len(randArray1))
print('************************************')
randArray2 = np.random.rand(3,3,3)
print(randArray2)
print(randArray2.ndim, 'dimention')
print(randArray2.shape, 'shape')
print('length of an array ',len(randArray2))

[[0.29130622 0.99207505 0.76959105]
 [0.45074443 0.18730246 0.36797522]
 [0.63478708 0.58128267 0.54590911]]
2 dimention
(3, 3) shape
length of an array  3
************************************
[[[0.49080382 0.32882138 0.1928807 ]
  [0.99783684 0.39767726 0.73147673]
  [0.28335974 0.85725709 0.8986053 ]]

 [[0.50610805 0.08071729 0.3969454 ]
  [0.66925638 0.27521968 0.44026862]
  [0.54144585 0.46445297 0.12376617]]

 [[0.92595547 0.33072713 0.8491703 ]
  [0.79462251 0.53840701 0.07434087]
  [0.16195347 0.50491823 0.93041789]]]
3 dimention
(3, 3, 3) shape
length of an array  3
